flysystem:
    storages:
        my_storage:
            adapter: '%env(FLYSYSTEM_ADAPTER)%'
            options:
                # Options spécifiques à l'adaptateur
                directory: '%kernel.project_dir%/var/storage'  # Pour le stockage local
                client: '@Aws\S3\S3Client'  # Pour S3
                bucket: '%env(AWS_BUCKET_NAME)%'  # Pour S3
                prefix: 'uploads'