version: '3.7'

services:
    app:
        ports:
            - "9000:9000" # Expose le port PHP-FPM
        environment:
            XDEBUG_MODE: debug,develop
            XDEBUG_CONFIG: remote_enable=1 remote_autostart=1
        volumes:
            - ./:/var/www/html
            - ./docker/app/conf.d/opcache_preload_prod.ini:/usr/local/etc/php/conf.d/opcache_preload_prod.ini # Si vous utilisez un fichier de préchargement OPCache

    server:
        ports:
            - "8080:80" # Expose le port du serveur Nginx
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/snippets/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf

    database:
        ports:
            - "3306:3306" # Expose le port MySQL pour les connexions locales
        environment:
            MYSQL_ROOT_PASSWORD: symfony
            MYSQL_DATABASE: nursery
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
