version: '3.8'

services:
    app:
        build:
            context: .
            target: nurs-php-dev
        image: nurs:dev
        restart: on-failure
        volumes:
            - ./:/var/www/html
        depends_on:
            - localstack

    server:
        image: nginx:alpine
        restart: on-failure
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/default.conf

    database:
        image: mysql:8.0
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: symfony
            MYSQL_DATABASE: nursery
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony

    mercure:
        image: dunglas/mercure
        restart: unless-stopped
        environment:
            SERVER_NAME: ':80'
            MERCURE_PUBLISHER_JWT_KEY: 'hJl5v2MincKCOvpqbxJ83i76jDaafNZ27Vr+0My38pI='
            MERCURE_SUBSCRIBER_JWT_KEY: 'hJl5v2MincKCOvpqbxJ83i76jDaafNZ27Vr+0My38pI='
            MERCURE_EXTRA_DIRECTIVES: |
                cors_origins http://127.0.0.1:8000 http://localhost:3000
                allow_credentials true
        # Uncomment the following line to enable the development mode
        command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
        ports:
            - "80"
            - 8001:80
        volumes:
            - mercure_data:/data
            - mercure_config:/config

    localstack:
        container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
        image: localstack/localstack:s3-latest
        ports:
            - "127.0.0.1:4566:4566"
        environment:
            - DEBUG=${DEBUG:-0}
        volumes:
            - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
    mercure_data:
    mercure_config:
    localstack_data: